First commit
shahendaeldeeb/AddressBook pull request #1
Opened 2017-03-29 13:19 UTC by shahendaeldeeb

My new code

2017-03-29 18:02 UTC, mcherri requested changes
Nice start, I need to view it working :D

2017-03-29 18:02 UTC, mcherri commented on main.go
> +type contact_info struct{
I do not like _. Rename it to ContactInfo

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	ID 		int   `db:"id"`
- ID should be the first field as it is the primary key.
- ID should be Id

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	Contact_id int `db:"contactid"`
Should be ContactId

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	muxer.HandleFunc("/viewNumbers/{id}", telephone.ViewTelephonesHandler).Methods("GET")
- URLs should be all small letters
- Although making contact, userAccount, telephone as receivers is a good, but it has no use here.

2017-03-29 18:02 UTC, mcherri commented on main.go
> +var muxer = mux.NewRouter()
Why doing this here and not inside main()?

2017-03-29 18:02 UTC, mcherri commented on main.go
> +var db *sql.DB
This should be the returned value from initDb() and not global

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	defer db.Close()
This should be right after we return from initDb(). See below.

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	db,_ =sql.Open("mysql" , "root:shahenda_hassan@/mydatabase")
We need to handle errors

2017-03-29 18:02 UTC, mcherri commented on main.go
> +func verifyDatabase(w http.ResponseWriter , r *http.Request , next http.HandlerFunc){
Nice!

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		secret , _ := bcrypt.GenerateFromPassword([]byte(r.FormValue("password")) , bcrypt.DefaultCost)
Nice using bcrypt. Do you know why?

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		for  row.Next(){
This for should be an if

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		defer row.Close()
defer should be before the for

2017-03-29 18:02 UTC, mcherri commented on main.go
> +			err := bcrypt.CompareHashAndPassword(info.Password , []byte(r.FormValue("password")))
How do we know if the database returned an empty set?

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	contact.Name = r.FormValue("name")
Not 100% OOP

2017-03-29 18:02 UTC, mcherri commented on main.go
> +	stmt , err :=db.Prepare("delete from Contacts where id=?")
I don't have the SQL script of the database but do we need to delete all the phone number of this contact too?

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		p1.Numbers = append(p1.Numbers , tele)
I do not think this is working. Did you try this for multiple phone numbers?

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		p.Contacts = append(p.Contacts ,contact)
I need to see this working.

2017-03-29 18:02 UTC, mcherri commented on main.go
> +		panic(err)
Just making sure, if we have an error the whole application is down?

2017-03-30 18:00 UTC, shahendaeldeeb commented on main.go
> +		for  row.Next(){
done

2017-03-30 18:00 UTC, shahendaeldeeb commented on main.go
> +type contact_info struct{
done

2017-03-30 18:00 UTC, shahendaeldeeb commented on main.go
> +	ID 		int   `db:"id"`
done

2017-03-30 18:00 UTC, shahendaeldeeb commented on main.go
> +	Contact_id int `db:"contactid"`
done

2017-03-30 18:01 UTC, shahendaeldeeb commented on main.go
> +	defer db.Close()
done

2017-03-30 18:14 UTC, shahendaeldeeb commented on main.go
> +var muxer = mux.NewRouter()
i returned it in main

2017-03-30 18:14 UTC, shahendaeldeeb commented on main.go
> +	db,_ =sql.Open("mysql" , "root:shahenda_hassan@/mydatabase")
done

2017-03-30 18:34 UTC, shahendaeldeeb commented on main.go
> +		secret , _ := bcrypt.GenerateFromPassword([]byte(r.FormValue("password")) , bcrypt.DefaultCost)
as bcrypt is the library that generated a salt-password hash ,as each password is hashed the same way , if two users have the same password , they will have the same hash , we can prevent this by randomizing each hash , by appending a random string called salt ,which is stored in user account database .

2017-03-30 18:35 UTC, shahendaeldeeb commented on main.go
> +		defer row.Close()
done

2017-03-30 18:39 UTC, shahendaeldeeb commented on main.go
> +	stmt , err :=db.Prepare("delete from Contacts where id=?")
At SQL script , i added "on delete cascade" , which automatically if i deleted a contact it will delete all his phone numbers .

2017-03-30 18:57 UTC, shahendaeldeeb commented on main.go
> +var db *sql.DB
done

2017-04-01 13:31 UTC, shahendaeldeeb commented on main.go
> +		p1.Numbers = append(p1.Numbers , tele)
yes , it works

2017-04-02 16:19 UTC, shahendaeldeeb commented
@mcherri please check my last commit. :slightly_smiling_face:

2017-04-03 09:56 UTC, mcherri requested changes
Better but I still think I need to help you:
- Make it more OOP
- Error handling

2017-04-03 09:56 UTC, mcherri commented on main.go
> +type contactInfo struct{
Is contactInfo private? If not then it should be ContactInfo

2017-04-03 09:56 UTC, mcherri commented on main.go
> +	F  func(http.ResponseWriter, *http.Request ,http.HandlerFunc, *HandlersVars)
Is there a better name than F?

2017-04-03 09:56 UTC, mcherri commented on main.go
> +	F  func(http.ResponseWriter, *http.Request ,*HandlersVars)
Is there a better name than F?

2017-04-04 08:43 UTC, shahendaeldeeb commented on main.go
> +type contactInfo struct{
done

2017-04-04 08:46 UTC, shahendaeldeeb commented on main.go
> +	F  func(http.ResponseWriter, *http.Request ,*HandlersVars)
done

2017-04-04 08:46 UTC, shahendaeldeeb commented on main.go
> +	F  func(http.ResponseWriter, *http.Request ,http.HandlerFunc, *HandlersVars)
done

2017-04-11 11:59 UTC, mcherri requested changes
OOP issues

2017-04-11 11:59 UTC, mcherri commented on main.go
> +		p := tele.ViewTelephonesHandler(tele.ContactId,tele.Number,tele.Num_id,mux.Vars(r)["id"], usedDataBase)
I think I will need to help you in this.

2017-04-12 09:46 UTC, mcherri reviewed
I will look with you

2017-04-25 08:12 UTC, mcherri approved these changes
:100:

2017-04-25 08:12 UTC, merged